name: publish-plugin

on:
    workflow_dispatch:

jobs:
    publish-plugin:
        runs-on: ubuntu-latest
        env:
            WINDY_API_KEY: '${{ secrets.WINDY_API_KEY }}'
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'
            - name: Install Node dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Create Archive
              run: |
                  cd dist
                  echo "{\"repositoryName\": \"${{ github.repository }}\", \"commitSha\": \"${{ github.sha }}\", \"repositoryOwner\": \"${{ github.repository_owner }}\"}" > /tmp/plugin-info.json
                  mv plugin.json /tmp
                  jq -s '.[0] * .[1]' /tmp/plugin.json /tmp/plugin-info.json > plugin.json
                  tar cf ../plugin.tar .
            - name: Publish Plugin
              run: |
                  if [ -z "$WINDY_API_KEY" ]; then
                    echo "Secret WINDY_API_KEY is not configured" >&2
                    exit 1
                  fi
                  curl -s --fail-with-body -XPOST 'https://api.windy.com/api/windy-plugins/v1.0/upload' -H "x-windy-api-key: ${WINDY_API_KEY}" -F "plugin_archive=@plugin.tar"
            - name: Save Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: plugin-archive
                  path: plugin.tar